// src/service-worker.js
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

// Precache files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Cache strategies
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({
    cacheName: 'pages-cache',
    networkTimeoutSeconds: 3,
  })
);

registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [{
      cacheKeyWillBeUsed: async ({ request }) => {
        return `${request.url}?timestamp=${Date.now()}`;
      },
    }],
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://story-api.dicoding.dev',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [{
      cacheWillUpdate: async ({ response }) => {
        return response.status === 200 ? response : null;
      },
    }],
  })
);

// Service Worker lifecycle events
self.addEventListener('install', (event) => {
  console.log('Service Worker installing...');
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  console.log('Service Worker activating...');
  event.waitUntil(clients.claim());
});

// Push notification handler
self.addEventListener('push', function(event) {
  console.log('Push notification received:', event);
  
  let notificationData = {
    title: 'Story App',
    body: 'Anda memiliki notifikasi baru!',
    icon: '/story-app-spa/icon-192.png',
    badge: '/story-app-spa/icon-192.png',
    tag: 'story-notification',
    requireInteraction: true,
    data: {
      url: '/story-app-spa/'
    },
    actions: [
      {
        action: 'view',
        title: '👀 Lihat',
        icon: '/story-app-spa/icon-192.png'
      },
      {
        action: 'close',
        title: '❌ Tutup'
      }
    ]
  };

  // Parse push data if available
  if (event.data) {
    try {
      const pushData = event.data.json();
      console.log('Parsed push data:', pushData);
    
      if (pushData.title) {
        notificationData.title = pushData.title;
      }
      
      if (pushData.options) {
        if (pushData.options.body) {
          notificationData.body = pushData.options.body;
        }
        if (pushData.options.icon) {
          notificationData.icon = pushData.options.icon;
        }
        if (pushData.options.data) {
          notificationData.data = pushData.options.data;
        }
      }
      
    } catch (e) {
      console.log('Push data is not JSON, using as text');
      notificationData.body = event.data.text();
    }
  }

  event.waitUntil(
    self.registration.showNotification(notificationData.title, notificationData)
  );
});

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  console.log('Notification clicked:', event);
  event.notification.close();

  if (event.action === 'view' || !event.action) {
    event.waitUntil(
      clients.matchAll({ type: 'window' }).then((clientList) => {
        // Cek apakah ada window yang sudah terbuka
        for (const client of clientList) {
          if (client.url.includes('/story-app-spa/') && 'focus' in client) {
            return client.focus();
          }
        }
        
        // Jika tidak ada window yang terbuka, buka yang baru
        if (clients.openWindow) {
          return clients.openWindow('/story-app-spa/');
        }
      })
    );
  }
});

// Background sync handler
self.addEventListener('sync', (event) => {
  console.log('Background sync triggered:', event.tag);
  
  if (event.tag === 'background-sync') {
    event.waitUntil(doBackgroundSync());
  }
});

async function doBackgroundSync() {
  console.log('Background sync processing...');
  // Implementasi background sync untuk sinkronisasi data offline
  try {
    const pendingData = await getPendingDataFromIndexedDB();
    if (pendingData && pendingData.length > 0) {
      await syncDataToServer(pendingData);
    }
  } catch (error) {
    console.error('Background sync failed:', error);
  }
}

// Helper functions for background sync
async function getPendingDataFromIndexedDB() {
  return [];
}

async function syncDataToServer(data) {
  console.log('Syncing data to server:', data);
}